version: '3.8'

services:
  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
      - ./.env:/var/www/html/.env
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./api/logs:/var/www/html/logs
      - /var/www/html/vendor
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - app-network

  websocket:
    build: ./websocket
    container_name: websocket
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./websocket:/app
      - /app/node_modules
      - ./.env:/app/.env
    depends_on:
      - api
      - redis
      - rabbitmq
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
#      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: root
#      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./api/mysql-init/:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      PMA_ARBITRARY: "1"
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis-data: