CREATE DATABASE IF NOT EXISTS jackpot_db;
USE jackpot_db;

CREATE TABLE IF NOT EXISTS jackpot (
    id INT PRIMARY KEY AUTO_INCREMENT,
    total FLOAT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tickets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    amount FLOAT NOT NULL,
    jackpot_fee FLOAT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO jackpot (id, total) VALUES (1, 0) ON DUPLICATE KEY UPDATE total = total;